### ISSUE TITLE
Simplify controller a little

### ISSUE THREAD

**Issue by srpeirce** [Intoware/cards-for-productivity#1]
Hey, I just took a look at your project after seeing a post on LinkedIn.
I might be wrong but I think you can simplify your  Session Controller code.
Because it has the `[ApiController] ` attribute I don't think you need the '[FromBody]` attribute on your Post methods, and I don't think you need to explicitly check for valid modelstate.

https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-3.1

Thanks,
Steve

**Comment by jamesikanos** [comment]
Thanks Steve. Will review and get back to you.
